- hosts: 10.0.1.214
  roles:
    - /etc/ansible/roles/role-ossec/roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: 10.0.1.204
        port: 1514
        protocol: udp
        api_port: 55000
        api_proto: 'http'
        api_user: ansible
    wazuh_agent_authd:
      enable: true
      port: 1515
      ssl_agent_ca: null
      ssl_auto_negotiate: 'no'
